In [13]:
import numpy as np

In [8]:
# 1_Create a 1D NumPy array containing the numbers from 10 to 50 (inclusive) with a step of 5

Darray = np.arange(10, 51,5)
print(Darray)

[10 15 20 25 30 35 40 45 50]


In [14]:
# 2_Create a 4×6 array filled with zeros, then fill its third row (index 2) with the value 99

Zeros2d = np.zeros((4,6))
Zeros2d[2, :] = 99
print(Zeros2d)


[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [99. 99. 99. 99. 99. 99.]
 [ 0.  0.  0.  0.  0.  0.]]


In [15]:
# 3_ Given the array:
 # arr = np.array([12, 45, 7, 19, 88, 3, 56, 91, 24, 67])
 # Print all elements that are greater than 50.

arr = np.array([12, 45, 7, 19, 88, 3, 56, 91, 24, 67])
print(arr[arr > 50])


[88 56 91 67]


In [16]:
#4_ Create a 5×5 identity matrix, then change its main diagonal (from top-left to bottom-right) to the values [10, 20, 30, 40, 50]

mat = np.eye(5)
np.fill_diagonal(mat, [10, 20, 30, 40, 50])
print(mat)


[[10.  0.  0.  0.  0.]
 [ 0. 20.  0.  0.  0.]
 [ 0.  0. 30.  0.  0.]
 [ 0.  0.  0. 40.  0.]
 [ 0.  0.  0.  0. 50.]]


In [17]:
#5_ Extract a,b,c using slicing:
 # let x equal
x = np.arange(1, 21).reshape(4, 5)
print(x)

# a.The last two rows
a = x[-2:, :]

# b. The third column
b = x[:, 2]

# c.the 3×3 submatrix in the top-right corner
c = x[:3, -3:]

print(a)
print(b)
print(c)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[11 12 13 14 15]
 [16 17 18 19 20]]
[ 3  8 13 18]
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [18]:
#6_ Given two arrays:
 # Compute a + b and explain the shape of the result.

a = np.array([1, 2, 3, 4])
b = np.array([[10], [20], [30]])
print(a+b)

# explanation (Dimensions are compatible if they are equal or one of them is 1
# a is broadcast across rows
# b is broadcast across columns)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [5]:
#7_ Normalize the following array to the range [0, 1]:

data = np.array([150, 220, 90, 300, 180, 45])
normalized_data = (data - data.min()) / (data.max() - data.min())
print(normalized_data)



[0.41176471 0.68627451 0.17647059 1.         0.52941176 0.        ]


In [4]:
#8_  Standardize (z-score) the same array from question 7:

data = np.array([150, 220, 90, 300, 180, 45])
mean = data.mean()
z_scores = (data-mean) / data.std()
print(z_scores)



[-0.16988961  0.66956492 -0.88942206  1.62894153  0.18987662 -1.42907141]


In [9]:
# 9_ Given the 2D array:
  # a. Compute the mean of each row
  # b. Compute the sum of each column
  # c. Find the maximum value in the entire matrix and its position (row, column)

mat = np.array([
    [4, 8, 1, 12],
    [7, 3, 9, 5],
     [11, 2, 6, 10],
    [15, 0, 14, 13]])

# a. Compute the mean of each row
row_mean = mat.mean(axis=1)
print("a = ", row_mean)

# b. Compute the sum of each column
col_sum = mat.sum(axis=0)
print("b = ", col_sum)

# c. Find the maximum value in the entire matrix and its position (row, column)
max_value = mat.max()
row, col = np.unravel_index(mat.argmax(), mat.shape)
print(f"Max value = {max_value}, Position = (row={row}, column={col})")


a =  [ 6.25  6.    7.25 10.5 ]
b =  [37 13 30 40]
Max value = 15, Position = (row=3, column=0)


In [19]:
# 10_ Reshape the array np.arange(36) into a 3D array of shape (3, 4, 3)

array = np.arange(36).reshape(3, 4, 3)
print(array)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [20]:
# 11_ Given
 # Reverse the order of rows and columns (flip both)
arr = np.arange(1, 17).reshape(4, 4)
print(arr)
flipped_arr = np.flip(arr)
print(flipped_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [23]:
# 12_ Given:
 # Get the names of people whose age is between 25 and 40 (inclusive).

ages = np.array([23, 45, 19, 34, 28, 51, 17, 39])
names = np.array(["Ali", "Sara", "Omar", "Lina", "Khaled", "Nour", "Yara", "Hassan"])
mask = (ages >= 25) & (ages <= 40)
Req_Names = names[mask]
print(Req_Names)


['Lina' 'Khaled' 'Hassan']


In [26]:
# 13_ Using the same ages and names arrays:
 # Replace all ages less than 20 with 20

ages = np.array([23, 45, 19, 34, 28, 51, 17, 39])
ages[ages < 20] = 20
print(ages)


[23 45 20 34 28 51 20 39]


In [44]:
# 14_ Create a 6×6 array filled with random integers between 1 and 100 (inclusive). Then set the seed to 123 first

np.random.seed(123)
Ran_arr = np.random.randint(1, 101, size=(6, 6))
print(Ran_arr)



[[ 67  93  99  18  84  58]
 [ 87  98  97  48  74  33]
 [ 47  97  26  84  79  37]
 [ 97  81  69  50  56  68]
 [  3  85  40  67  85  48]
 [ 62  49   8 100  93  53]]


In [45]:
# 15_ Create an array of 10 random numbers from a normal distribution with mean 100 and standard deviation 15

random_numbers = np.random.normal(loc=100, scale=15, size=10)
print(random_numbers)



[127.06686834  85.51674961  80.25279948  90.61322265  95.09580659
  95.37686206 112.40676196 116.06172126  54.16633874 115.08897902]


In [49]:
# 16_ From the list:
 # Randomly select 3 different colors without replacement

colors = ["red", "blue", "green", "yellow", "purple"]
selected_colors = np.random.choice(colors, size=3, replace=False)
print(selected_colors)



['red' 'blue' 'green']


In [54]:
# 17_ Shuffle the numbers from 1 to 20 in place

numbers = np.arange(1, 21)
np.random.shuffle(numbers)
print(numbers)


[ 3  1 19 13  4  5  6 12 17 10 11  8 18 16  2  7 15  9 20 14]
